# Plugin by TheViperShow -
# Remember to leave a review if you
# are enjoying this plugin.
main:
  #should we stop people from going on the roof?
  cancel: true
  #this value is the minimum time IN SECONDS that needs to pass to triggers the executables again.
  #NOTE: set this to -1 to disable the time check delay (not recommended)
  executables-delay: 10
  # You can add as many commands as you want with the following placeholders:
  # %PLAYER% - The player who went on the Nether's roof.
  # %PREV_LOC% - His last position that wasn't on the Nether's roof.
  # %PREV_LOC_WORLD% - The world's name of his last safe position.
  # %ROOF_POS% - The illegal position where the player attempted to get on.
  # Positions will be replaced with a X Y Z format.
  punish-executables:
    - "minecraft:me %PLAYER% Has tried to reach the nether's roof!"